[tool.isort]
profile = "black"
force_to_top = "typing"
from_first = true
combine_as_imports = true
known_first_party = "mautrix"
line_length = 99
skip = ["maubot/management/frontend"]

[tool.black]
line-length = 99
target-version = ["py38"]
force-exclude = "maubot/management/frontend"
